##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:28 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (32.74, 31.984, 27.828)
Vclist_setupGrid:  Grid lower corner = (-15.928, -15.885, -13.856)
Vclist_assignAtoms:  Have 343316 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.104229
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.222360e-01
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.110000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 8.583000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.365630e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.447437e-15
Vprtstp: contraction number = 2.447437e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 3.670000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 9.155000e-03
Vpmg_setPart:  lower corner = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  upper corner = (48.3425, 48.107, 47.708)
Vpmg_setPart:  actual minima = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  actual maxima = (48.3425, 48.107, 47.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.379960e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:28 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-47.6575, -47.893, -48.292)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (32.74, 31.984, 27.828)
Vclist_setupGrid:  Grid lower corner = (-15.928, -15.885, -13.856)
Vclist_assignAtoms:  Have 343316 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.103673
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- New mesh maxs = 32.3425, 32.107, 31.708
VPMG::focusFillBound -- Old mesh mins = -47.6575, -47.893, -48.292
VPMG::focusFillBound -- Old mesh maxs = 48.3425, 48.107, 47.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.360710e-01
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.497000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.930000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.506000e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.757507e-02
Vprtstp: contraction number = 4.757507e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.027101e-03
Vprtstp: contraction number = 1.056667e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.604770e-04
Vprtstp: contraction number = 1.114911e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.496223e-05
Vprtstp: contraction number = 1.159052e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 7.706496e-06
Vprtstp: contraction number = 1.186304e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.302600e-07
Vprtstp: contraction number = 1.207112e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.621000e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 2.233900e-02
Vpmg_setPart:  lower corner = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  upper corner = (32.3425, 32.107, 31.708)
Vpmg_setPart:  actual minima = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  actual maxima = (32.3425, 32.107, 31.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.892800e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:28 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-31.6575, -31.893, -32.292)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (32.74, 31.984, 27.828)
Vclist_setupGrid:  Grid lower corner = (-15.928, -15.885, -13.856)
Vclist_assignAtoms:  Have 343316 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.104449
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -19.6575, -19.893, -20.292
VPMG::focusFillBound -- New mesh maxs = 20.3425, 20.107, 19.708
VPMG::focusFillBound -- Old mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- Old mesh maxs = 32.3425, 32.107, 31.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.828220e-01
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.500200e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 4.450900e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.914490e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.154521e-01
Vprtstp: contraction number = 1.154521e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.327111e-02
Vprtstp: contraction number = 1.149491e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.610117e-03
Vprtstp: contraction number = 1.213250e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.079025e-04
Vprtstp: contraction number = 1.291226e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.872277e-05
Vprtstp: contraction number = 1.381550e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.252307e-06
Vprtstp: contraction number = 1.480466e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.633780e-07
Vprtstp: contraction number = 1.560043e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.042100e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 2.688710e-01
Vpmg_setPart:  lower corner = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  upper corner = (20.3425, 20.107, 19.708)
Vpmg_setPart:  actual minima = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  actual maxima = (20.3425, 20.107, 19.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 2.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.664320e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:29 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (21, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 26 atoms
Valist_getStatistics:  Max atom coordinate:  (3.678, 3.566, 2.513)
Valist_getStatistics:  Min atom coordinate:  (-3.853, -3.088, -2.289)
Valist_getStatistics:  Molecule center:  (-0.0875, 0.239, 0.112)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 6.06921
Vpbe_ctor2:  solute dimensions = 10.131 x 9.254 x 7.512
Vpbe_ctor2:  solute charge = -0.0003
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 20 x 18 x 15 table
Vclist_ctor2:  Using 20 x 18 x 15 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (25.139, 24.262, 22.41)
Vclist_setupGrid:  Grid lower corner = (-12.657, -11.892, -11.093)
Vclist_assignAtoms:  Have 27932 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.009558
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.488400e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (021, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.540000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 4.187200e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.996500e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.926421e-15
Vprtstp: contraction number = 2.926421e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.300000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 4.306800e-02
Vpmg_setPart:  lower corner = (-40.0875, -23.761, -23.833)
Vpmg_setPart:  upper corner = (39.9125, 24.239, 24.167)
Vpmg_setPart:  actual minima = (-40.0875, -23.761, -23.833)
Vpmg_setPart:  actual maxima = (39.9125, 24.239, 24.167)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.231500e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:29 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 3, dime = (49, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 26 atoms
Valist_getStatistics:  Max atom coordinate:  (3.678, 3.566, 2.513)
Valist_getStatistics:  Min atom coordinate:  (-3.853, -3.088, -2.289)
Valist_getStatistics:  Molecule center:  (-0.0875, 0.239, 0.112)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 21 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-40.0875, -23.761, -23.833)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 21 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 6.06921
Vpbe_ctor2:  solute dimensions = 10.131 x 9.254 x 7.512
Vpbe_ctor2:  solute charge = -0.0003
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 20 x 18 x 15 table
Vclist_ctor2:  Using 20 x 18 x 15 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (25.139, 24.262, 22.41)
Vclist_setupGrid:  Grid lower corner = (-12.657, -11.892, -11.093)
Vclist_assignAtoms:  Have 27932 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.009226
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -24.0875, -15.761, -15.833
VPMG::focusFillBound -- New mesh maxs = 23.9125, 16.239, 16.167
VPMG::focusFillBound -- Old mesh mins = -40.0875, -23.761, -23.833
VPMG::focusFillBound -- Old mesh maxs = 39.9125, 24.239, 24.167
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 3.612000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (049, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 2.206000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (025, 017, 017)
Vbuildops: Galer: (013, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 7.557000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.379800e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 7.556723e-02
Vprtstp: contraction number = 7.556723e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 8.240359e-03
Vprtstp: contraction number = 1.090467e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 9.374915e-04
Vprtstp: contraction number = 1.137683e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.101487e-04
Vprtstp: contraction number = 1.174930e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.315937e-05
Vprtstp: contraction number = 1.194691e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.590639e-06
Vprtstp: contraction number = 1.208750e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.934095e-07
Vprtstp: contraction number = 1.215923e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.667700e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 3.744900e-02
Vpmg_setPart:  lower corner = (-24.0875, -15.761, -15.833)
Vpmg_setPart:  upper corner = (23.9125, 16.239, 16.167)
Vpmg_setPart:  actual minima = (-24.0875, -15.761, -15.833)
Vpmg_setPart:  actual maxima = (23.9125, 16.239, 16.167)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.127200e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Fri Aug 27 07:53:29 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 3, dime = (49, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 26 atoms
Valist_getStatistics:  Max atom coordinate:  (3.678, 3.566, 2.513)
Valist_getStatistics:  Min atom coordinate:  (-3.853, -3.088, -2.289)
Valist_getStatistics:  Molecule center:  (-0.0875, 0.239, 0.112)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 49 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-24.0875, -15.761, -15.833)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 49 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 6.06921
Vpbe_ctor2:  solute dimensions = 10.131 x 9.254 x 7.512
Vpbe_ctor2:  solute charge = -0.0003
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7163.11
Vpbe_ctor2:  Constructing Vclist with 20 x 18 x 15 table
Vclist_ctor2:  Using 20 x 18 x 15 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 4.5 max radius
Vclist_setupGrid:  Grid lengths = (25.139, 24.262, 22.41)
Vclist_setupGrid:  Grid lower corner = (-12.657, -11.892, -11.093)
Vclist_assignAtoms:  Have 27932 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 483.051
Vacc_storeParms:  Using 4892-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.009213
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -12.0875, -7.761, -7.833
VPMG::focusFillBound -- New mesh maxs = 11.9125, 8.239, 8.167
VPMG::focusFillBound -- Old mesh mins = -24.0875, -15.761, -15.833
VPMG::focusFillBound -- Old mesh maxs = 23.9125, 16.239, 16.167
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 7.585600e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (049, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 2.209000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (025, 017, 017)
Vbuildops: Galer: (013, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 7.518000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.514470e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.423951e-01
Vprtstp: contraction number = 1.423951e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.756363e-02
Vprtstp: contraction number = 1.233443e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.262063e-03
Vprtstp: contraction number = 1.287925e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 3.096969e-04
Vprtstp: contraction number = 1.369090e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 4.452260e-05
Vprtstp: contraction number = 1.437619e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 6.608247e-06
Vprtstp: contraction number = 1.484245e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.005598e-06
Vprtstp: contraction number = 1.521731e-01
Vprtstp: iteration = 8
Vprtstp: relative residual = 1.563763e-07
Vprtstp: contraction number = 1.555059e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 3.051700e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 4.124800e-02
Vpmg_setPart:  lower corner = (-12.0875, -7.761, -7.833)
Vpmg_setPart:  upper corner = (11.9125, 8.239, 8.167)
Vpmg_setPart:  actual minima = (-12.0875, -7.761, -7.833)
Vpmg_setPart:  actual maxima = (11.9125, 8.239, 8.167)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 2.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 2.140960e-01
