##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:35 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (41.58, 16.05, 31.694)
Valist_getStatistics:  Min atom coordinate:  (27.691, 1.188, 20.578)
Valist_getStatistics:  Molecule center:  (34.6355, 8.619, 26.136)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.87653
Vpbe_ctor2:  solute dimensions = 16.428 x 17.462 x 13.271
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 32 x 34 x 26 table
Vclist_ctor2:  Using 32 x 34 x 26 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (24.397, 25.37, 21.624)
Vclist_setupGrid:  Grid lower corner = (22.437, -4.066, 15.324)
Vclist_assignAtoms:  Have 169674 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.015628
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.385900e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 7.500000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.205000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.661100e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.235864e-15
Vprtstp: contraction number = 2.235864e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.260000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.569000e-03
Vpmg_setPart:  lower corner = (-13.395, -39.381, -22.0455)
Vpmg_setPart:  upper corner = (82.605, 56.619, 73.9545)
Vpmg_setPart:  actual minima = (-13.395, -39.381, -22.0455)
Vpmg_setPart:  actual maxima = (82.605, 56.619, 73.9545)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.571700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:35 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (41.58, 16.05, 31.694)
Valist_getStatistics:  Min atom coordinate:  (27.691, 1.188, 20.578)
Valist_getStatistics:  Molecule center:  (34.6355, 8.619, 26.136)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-13.395, -39.381, -22.0455)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.87653
Vpbe_ctor2:  solute dimensions = 16.428 x 17.462 x 13.271
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 32 x 34 x 26 table
Vclist_ctor2:  Using 32 x 34 x 26 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (24.397, 25.37, 21.624)
Vclist_setupGrid:  Grid lower corner = (22.437, -4.066, 15.324)
Vclist_assignAtoms:  Have 169674 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013856
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 2.605, -23.381, -6.0455
VPMG::focusFillBound -- New mesh maxs = 66.605, 40.619, 57.9545
VPMG::focusFillBound -- Old mesh mins = -13.395, -39.381, -22.0455
VPMG::focusFillBound -- Old mesh maxs = 82.605, 56.619, 73.9545
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.761300e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.940000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.438000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.203000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 5.337150e-02
Vprtstp: contraction number = 5.337150e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.762540e-03
Vprtstp: contraction number = 1.079704e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 6.475549e-04
Vprtstp: contraction number = 1.123732e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 7.462189e-05
Vprtstp: contraction number = 1.152364e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.781771e-06
Vprtstp: contraction number = 1.176836e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.049904e-06
Vprtstp: contraction number = 1.195549e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.272147e-07
Vprtstp: contraction number = 1.211679e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.103000e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.495100e-02
Vpmg_setPart:  lower corner = (2.605, -23.381, -6.0455)
Vpmg_setPart:  upper corner = (66.605, 40.619, 57.9545)
Vpmg_setPart:  actual minima = (2.605, -23.381, -6.0455)
Vpmg_setPart:  actual maxima = (66.605, 40.619, 57.9545)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.363700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:35 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (41.58, 16.05, 31.694)
Valist_getStatistics:  Min atom coordinate:  (27.691, 1.188, 20.578)
Valist_getStatistics:  Molecule center:  (34.6355, 8.619, 26.136)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (2.605, -23.381, -6.0455)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.87653
Vpbe_ctor2:  solute dimensions = 16.428 x 17.462 x 13.271
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 32 x 34 x 26 table
Vclist_ctor2:  Using 32 x 34 x 26 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (24.397, 25.37, 21.624)
Vclist_setupGrid:  Grid lower corner = (22.437, -4.066, 15.324)
Vclist_assignAtoms:  Have 169674 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014134
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 14.605, -11.381, 5.9545
VPMG::focusFillBound -- New mesh maxs = 54.605, 28.619, 45.9545
VPMG::focusFillBound -- Old mesh mins = 2.605, -23.381, -6.0455
VPMG::focusFillBound -- Old mesh maxs = 66.605, 40.619, 57.9545
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.808800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.014000e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.894800e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.763470e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.145930e-01
Vprtstp: contraction number = 1.145930e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.278048e-02
Vprtstp: contraction number = 1.115293e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.537903e-03
Vprtstp: contraction number = 1.203322e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.067042e-04
Vprtstp: contraction number = 1.344065e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 3.042431e-05
Vprtstp: contraction number = 1.471877e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.741465e-06
Vprtstp: contraction number = 1.558446e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 7.647865e-07
Vprtstp: contraction number = 1.612975e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.176250e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.605450e-01
Vpmg_setPart:  lower corner = (14.605, -11.381, 5.9545)
Vpmg_setPart:  upper corner = (54.605, 28.619, 45.9545)
Vpmg_setPart:  actual minima = (14.605, -11.381, 5.9545)
Vpmg_setPart:  actual maxima = (54.605, 28.619, 45.9545)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.847310e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:36 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (30.823, 9.928, 15.159)
Valist_getStatistics:  Min atom coordinate:  (28.236, 5, 11.994)
Valist_getStatistics:  Molecule center:  (29.5295, 7.464, 13.5765)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (22.982, -0.254, 6.74)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002391
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 5.852000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.660000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 6.160000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.654400e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.493560e-15
Vprtstp: contraction number = 2.493560e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.300000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.661000e-03
Vpmg_setPart:  lower corner = (5.5295, -16.286, -10.3235)
Vpmg_setPart:  upper corner = (53.5295, 31.714, 37.6765)
Vpmg_setPart:  actual minima = (5.5295, -16.286, -10.3235)
Vpmg_setPart:  actual maxima = (53.5295, 31.714, 37.6765)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.545000e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:36 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (30.823, 9.928, 15.159)
Valist_getStatistics:  Min atom coordinate:  (28.236, 5, 11.994)
Valist_getStatistics:  Molecule center:  (29.5295, 7.464, 13.5765)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (5.5295, -16.286, -10.3235)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (22.982, -0.254, 6.74)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002367
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 13.5295, -8.286, -2.3235
VPMG::focusFillBound -- New mesh maxs = 45.5295, 23.714, 29.6765
VPMG::focusFillBound -- Old mesh mins = 5.5295, -16.286, -10.3235
VPMG::focusFillBound -- Old mesh maxs = 53.5295, 31.714, 37.6765
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.359000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.870000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.377000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.574300e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 7.778144e-02
Vprtstp: contraction number = 7.778144e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 7.404379e-03
Vprtstp: contraction number = 9.519468e-02
Vprtstp: iteration = 3
Vprtstp: relative residual = 7.379797e-04
Vprtstp: contraction number = 9.966802e-02
Vprtstp: iteration = 4
Vprtstp: relative residual = 7.556410e-05
Vprtstp: contraction number = 1.023932e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 7.860327e-06
Vprtstp: contraction number = 1.040220e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 8.278010e-07
Vprtstp: contraction number = 1.053138e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.292000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.314700e-02
Vpmg_setPart:  lower corner = (13.5295, -8.286, -2.3235)
Vpmg_setPart:  upper corner = (45.5295, 23.714, 29.6765)
Vpmg_setPart:  actual minima = (13.5295, -8.286, -2.3235)
Vpmg_setPart:  actual maxima = (45.5295, 23.714, 29.6765)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.539300e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:19:36 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (30.823, 9.928, 15.159)
Valist_getStatistics:  Min atom coordinate:  (28.236, 5, 11.994)
Valist_getStatistics:  Molecule center:  (29.5295, 7.464, 13.5765)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (13.5295, -8.286, -2.3235)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (22.982, -0.254, 6.74)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.000862
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 21.5295, -0.286, 5.6765
VPMG::focusFillBound -- New mesh maxs = 37.5295, 15.714, 21.6765
VPMG::focusFillBound -- Old mesh mins = 13.5295, -8.286, -2.3235
VPMG::focusFillBound -- Old mesh maxs = 45.5295, 23.714, 29.6765
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.705300e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.780000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.326000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.641900e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.411122e-01
Vprtstp: contraction number = 1.411122e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.853796e-02
Vprtstp: contraction number = 1.313704e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.541055e-03
Vprtstp: contraction number = 1.370731e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 3.520311e-04
Vprtstp: contraction number = 1.385374e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 4.883475e-05
Vprtstp: contraction number = 1.387228e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 6.806842e-06
Vprtstp: contraction number = 1.393852e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 9.530978e-07
Vprtstp: contraction number = 1.400206e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.100200e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.480500e-02
Vpmg_setPart:  lower corner = (21.5295, -0.286, 5.6765)
Vpmg_setPart:  upper corner = (37.5295, 15.714, 21.6765)
Vpmg_setPart:  actual minima = (21.5295, -0.286, 5.6765)
Vpmg_setPart:  actual maxima = (37.5295, 15.714, 21.6765)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.795100e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013838
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.054300e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 7.500000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.249000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.478800e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.299541e-15
Vprtstp: contraction number = 2.299541e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.290000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.615000e-03
Vpmg_setPart:  lower corner = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  upper corner = (48.3425, 48.107, 47.708)
Vpmg_setPart:  actual minima = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  actual maxima = (48.3425, 48.107, 47.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.391800e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-47.6575, -47.893, -48.292)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.016275
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- New mesh maxs = 32.3425, 32.107, 31.708
VPMG::focusFillBound -- Old mesh mins = -47.6575, -47.893, -48.292
VPMG::focusFillBound -- Old mesh maxs = 48.3425, 48.107, 47.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 3.109500e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.045000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.437000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.017900e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.425000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.345000e-02
Vpmg_setPart:  lower corner = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  upper corner = (32.3425, 32.107, 31.708)
Vpmg_setPart:  actual minima = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  actual maxima = (32.3425, 32.107, 31.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.384900e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-31.6575, -31.893, -32.292)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013828
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -19.6575, -19.893, -20.292
VPMG::focusFillBound -- New mesh maxs = 20.3425, 20.107, 19.708
VPMG::focusFillBound -- Old mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- Old mesh maxs = 32.3425, 32.107, 31.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.636800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.036200e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.956700e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.735460e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.215960e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.655370e-01
Vpmg_setPart:  lower corner = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  upper corner = (20.3425, 20.107, 19.708)
Vpmg_setPart:  actual minima = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  actual maxima = (20.3425, 20.107, 19.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.892900e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (1.159, 2.597, 1.146)
Valist_getStatistics:  Min atom coordinate:  (-1.428, -2.331, -2.019)
Valist_getStatistics:  Molecule center:  (-0.1345, 0.133, -0.4365)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (-6.682, -7.585, -7.273)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002389
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 5.879000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.840000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 6.128000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.685400e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.730777e-15
Vprtstp: contraction number = 2.730777e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.540000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.691000e-03
Vpmg_setPart:  lower corner = (-24.1345, -23.617, -24.3365)
Vpmg_setPart:  upper corner = (23.8655, 24.383, 23.6635)
Vpmg_setPart:  actual minima = (-24.1345, -23.617, -24.3365)
Vpmg_setPart:  actual maxima = (23.8655, 24.383, 23.6635)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.570500e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (1.159, 2.597, 1.146)
Valist_getStatistics:  Min atom coordinate:  (-1.428, -2.331, -2.019)
Valist_getStatistics:  Molecule center:  (-0.1345, 0.133, -0.4365)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-24.1345, -23.617, -24.3365)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (-6.682, -7.585, -7.273)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002049
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -16.1345, -15.617, -16.3365
VPMG::focusFillBound -- New mesh maxs = 15.8655, 16.383, 15.6635
VPMG::focusFillBound -- Old mesh mins = -24.1345, -23.617, -24.3365
VPMG::focusFillBound -- Old mesh maxs = 23.8655, 24.383, 23.6635
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.537500e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.049000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.428000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.788400e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 7.778144e-02
Vprtstp: contraction number = 7.778144e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 7.404379e-03
Vprtstp: contraction number = 9.519468e-02
Vprtstp: iteration = 3
Vprtstp: relative residual = 7.379797e-04
Vprtstp: contraction number = 9.966802e-02
Vprtstp: iteration = 4
Vprtstp: relative residual = 7.556410e-05
Vprtstp: contraction number = 1.023932e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 7.860327e-06
Vprtstp: contraction number = 1.040220e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 8.278010e-07
Vprtstp: contraction number = 1.053138e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.217000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.324100e-02
Vpmg_setPart:  lower corner = (-16.1345, -15.617, -16.3365)
Vpmg_setPart:  upper corner = (15.8655, 16.383, 15.6635)
Vpmg_setPart:  actual minima = (-16.1345, -15.617, -16.3365)
Vpmg_setPart:  actual maxima = (15.8655, 16.383, 15.6635)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.837700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:58:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 13 atoms
Valist_getStatistics:  Max atom coordinate:  (1.159, 2.597, 1.146)
Valist_getStatistics:  Min atom coordinate:  (-1.428, -2.331, -2.019)
Valist_getStatistics:  Molecule center:  (-0.1345, 0.133, -0.4365)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-16.1345, -15.617, -16.3365)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.851
Vpbe_ctor2:  solute dimensions = 5.187 x 7.028 x 5.965
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 10 x 14 x 11 table
Vclist_ctor2:  Using 10 x 14 x 11 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (13.095, 15.436, 13.673)
Vclist_setupGrid:  Grid lower corner = (-6.682, -7.585, -7.273)
Vclist_assignAtoms:  Have 4482 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.000881
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -8.1345, -7.617, -8.3365
VPMG::focusFillBound -- New mesh maxs = 7.8655, 8.383, 7.6635
VPMG::focusFillBound -- Old mesh mins = -16.1345, -15.617, -16.3365
VPMG::focusFillBound -- Old mesh maxs = 15.8655, 16.383, 15.6635
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.711000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.076000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.440000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.377100e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.411122e-01
Vprtstp: contraction number = 1.411122e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.853796e-02
Vprtstp: contraction number = 1.313704e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.541055e-03
Vprtstp: contraction number = 1.370731e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 3.520311e-04
Vprtstp: contraction number = 1.385374e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 4.883475e-05
Vprtstp: contraction number = 1.387228e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 6.806842e-06
Vprtstp: contraction number = 1.393852e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 9.530978e-07
Vprtstp: contraction number = 1.400206e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.109700e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.514800e-02
Vpmg_setPart:  lower corner = (-8.1345, -7.617, -8.3365)
Vpmg_setPart:  upper corner = (7.8655, 8.383, 7.6635)
Vpmg_setPart:  actual minima = (-8.1345, -7.617, -8.3365)
Vpmg_setPart:  actual maxima = (7.8655, 8.383, 7.6635)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.559900e-02
