##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:23 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.017195
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.384000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.800000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.487000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.703600e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.313577e-15
Vprtstp: contraction number = 2.313577e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 3.680000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.018000e-03
Vpmg_setPart:  lower corner = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  upper corner = (53.3495, 56.54, 65.504)
Vpmg_setPart:  actual minima = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  actual maxima = (53.3495, 56.54, 65.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.652200e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:23 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-42.6505, -39.46, -30.496)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014288
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- New mesh maxs = 37.3495, 40.54, 49.504
VPMG::focusFillBound -- Old mesh mins = -42.6505, -39.46, -30.496
VPMG::focusFillBound -- Old mesh maxs = 53.3495, 56.54, 65.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.845000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.950000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.383000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.380100e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.349000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.325100e-02
Vpmg_setPart:  lower corner = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  upper corner = (37.3495, 40.54, 49.504)
Vpmg_setPart:  actual minima = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  actual maxima = (37.3495, 40.54, 49.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.435200e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:23 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-26.6505, -23.46, -14.496)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.018601
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -14.6505, -11.46, -2.496
VPMG::focusFillBound -- New mesh maxs = 25.3495, 28.54, 37.504
VPMG::focusFillBound -- Old mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- Old mesh maxs = 37.3495, 40.54, 49.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.068950e-01
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.029000e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.289200e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.882970e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.266730e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.737250e-01
Vpmg_setPart:  lower corner = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  upper corner = (25.3495, 28.54, 37.504)
Vpmg_setPart:  actual minima = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  actual maxima = (25.3495, 28.54, 37.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.133790e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:24 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (14.577, 30.176, 28.786)
Valist_getStatistics:  Min atom coordinate:  (10.769, 26.031, 22.678)
Valist_getStatistics:  Molecule center:  (12.673, 28.1035, 25.732)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (5.515, 20.777, 17.424)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.003314
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 5.696000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.900000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.400000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.597300e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.489959e-15
Vprtstp: contraction number = 2.489959e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.410000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.776000e-03
Vpmg_setPart:  lower corner = (-11.227, 4.1035, 1.732)
Vpmg_setPart:  upper corner = (36.773, 52.1035, 49.732)
Vpmg_setPart:  actual minima = (-11.227, 4.1035, 1.732)
Vpmg_setPart:  actual maxima = (36.773, 52.1035, 49.732)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.488900e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:24 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (14.577, 30.176, 28.786)
Valist_getStatistics:  Min atom coordinate:  (10.769, 26.031, 22.678)
Valist_getStatistics:  Molecule center:  (12.673, 28.1035, 25.732)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-11.227, 4.1035, 1.732)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (5.515, 20.777, 17.424)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001661
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -3.227, 12.1035, 9.732
VPMG::focusFillBound -- New mesh maxs = 28.773, 44.1035, 41.732
VPMG::focusFillBound -- Old mesh mins = -11.227, 4.1035, 1.732
VPMG::focusFillBound -- Old mesh maxs = 36.773, 52.1035, 49.732
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.417600e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.037000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.346000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.575500e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 6.511535e-02
Vprtstp: contraction number = 6.511535e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 7.875842e-03
Vprtstp: contraction number = 1.209522e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 9.610774e-04
Vprtstp: contraction number = 1.220285e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.194851e-04
Vprtstp: contraction number = 1.243241e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.494384e-05
Vprtstp: contraction number = 1.250687e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.871364e-06
Vprtstp: contraction number = 1.252265e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 2.345549e-07
Vprtstp: contraction number = 1.253390e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.089100e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.479500e-02
Vpmg_setPart:  lower corner = (-3.227, 12.1035, 9.732)
Vpmg_setPart:  upper corner = (28.773, 44.1035, 41.732)
Vpmg_setPart:  actual minima = (-3.227, 12.1035, 9.732)
Vpmg_setPart:  actual maxima = (28.773, 44.1035, 41.732)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.835100e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:27:24 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (14.577, 30.176, 28.786)
Valist_getStatistics:  Min atom coordinate:  (10.769, 26.031, 22.678)
Valist_getStatistics:  Molecule center:  (12.673, 28.1035, 25.732)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-3.227, 12.1035, 9.732)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (5.515, 20.777, 17.424)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001313
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 4.773, 20.1035, 17.732
VPMG::focusFillBound -- New mesh maxs = 20.773, 36.1035, 33.732
VPMG::focusFillBound -- Old mesh mins = -3.227, 12.1035, 9.732
VPMG::focusFillBound -- Old mesh maxs = 28.773, 44.1035, 41.732
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.996200e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.008000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.358000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.955200e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.392249e-01
Vprtstp: contraction number = 1.392249e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.686478e-02
Vprtstp: contraction number = 1.211334e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.105234e-03
Vprtstp: contraction number = 1.248301e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.663759e-04
Vprtstp: contraction number = 1.265303e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 3.380220e-05
Vprtstp: contraction number = 1.268966e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.313359e-06
Vprtstp: contraction number = 1.276059e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 5.538063e-07
Vprtstp: contraction number = 1.283933e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.079800e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.468800e-02
Vpmg_setPart:  lower corner = (4.773, 20.1035, 17.732)
Vpmg_setPart:  upper corner = (20.773, 36.1035, 33.732)
Vpmg_setPart:  actual minima = (4.773, 20.1035, 17.732)
Vpmg_setPart:  actual maxima = (20.773, 36.1035, 33.732)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.224900e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013866
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.977600e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.900000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.236000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.403300e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.299541e-15
Vprtstp: contraction number = 2.299541e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.290000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.593000e-03
Vpmg_setPart:  lower corner = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  upper corner = (48.3425, 48.107, 47.708)
Vpmg_setPart:  actual minima = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  actual maxima = (48.3425, 48.107, 47.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.309700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-47.6575, -47.893, -48.292)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.015172
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- New mesh maxs = 32.3425, 32.107, 31.708
VPMG::focusFillBound -- Old mesh mins = -47.6575, -47.893, -48.292
VPMG::focusFillBound -- Old mesh maxs = 48.3425, 48.107, 47.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.981200e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.008000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.373000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.377000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.116000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.301100e-02
Vpmg_setPart:  lower corner = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  upper corner = (32.3425, 32.107, 31.708)
Vpmg_setPart:  actual minima = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  actual maxima = (32.3425, 32.107, 31.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.340800e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-31.6575, -31.893, -32.292)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013826
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -19.6575, -19.893, -20.292
VPMG::focusFillBound -- New mesh maxs = 20.3425, 20.107, 19.708
VPMG::focusFillBound -- Old mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- Old mesh maxs = 32.3425, 32.107, 31.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.615000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.031100e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.967800e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.679560e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.208640e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.648580e-01
Vpmg_setPart:  lower corner = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  upper corner = (20.3425, 20.107, 19.708)
Vpmg_setPart:  actual minima = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  actual maxima = (20.3425, 20.107, 19.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.827920e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (1.716, 1.942, 3.051)
Valist_getStatistics:  Min atom coordinate:  (-2.092, -2.203, -3.057)
Valist_getStatistics:  Molecule center:  (-0.188, -0.1305, -0.003)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (-7.346, -7.457, -8.311)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002287
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 5.002000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.140000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 8.150000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.829200e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.498016e-15
Vprtstp: contraction number = 2.498016e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.320000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 8.582000e-03
Vpmg_setPart:  lower corner = (-24.088, -24.1305, -24.003)
Vpmg_setPart:  upper corner = (23.912, 23.8695, 23.997)
Vpmg_setPart:  actual minima = (-24.088, -24.1305, -24.003)
Vpmg_setPart:  actual maxima = (23.912, 23.8695, 23.997)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.687100e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (1.716, 1.942, 3.051)
Valist_getStatistics:  Min atom coordinate:  (-2.092, -2.203, -3.057)
Valist_getStatistics:  Molecule center:  (-0.188, -0.1305, -0.003)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-24.088, -24.1305, -24.003)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (-7.346, -7.457, -8.311)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001262
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -16.088, -16.1305, -16.003
VPMG::focusFillBound -- New mesh maxs = 15.912, 15.8695, 15.997
VPMG::focusFillBound -- Old mesh mins = -24.088, -24.1305, -24.003
VPMG::focusFillBound -- Old mesh maxs = 23.912, 23.8695, 23.997
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.220800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.114000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.626000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.991000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 6.511535e-02
Vprtstp: contraction number = 6.511535e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 7.875842e-03
Vprtstp: contraction number = 1.209522e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 9.610774e-04
Vprtstp: contraction number = 1.220285e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.194851e-04
Vprtstp: contraction number = 1.243241e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.494384e-05
Vprtstp: contraction number = 1.250687e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.871364e-06
Vprtstp: contraction number = 1.252265e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 2.345549e-07
Vprtstp: contraction number = 1.253390e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.078400e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.509700e-02
Vpmg_setPart:  lower corner = (-16.088, -16.1305, -16.003)
Vpmg_setPart:  upper corner = (15.912, 15.8695, 15.997)
Vpmg_setPart:  actual minima = (-16.088, -16.1305, -16.003)
Vpmg_setPart:  actual maxima = (15.912, 15.8695, 15.997)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.245200e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:00:50 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 18 atoms
Valist_getStatistics:  Max atom coordinate:  (1.716, 1.942, 3.051)
Valist_getStatistics:  Min atom coordinate:  (-2.092, -2.203, -3.057)
Valist_getStatistics:  Molecule center:  (-0.188, -0.1305, -0.003)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-16.088, -16.1305, -16.003)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 4.7754
Vpbe_ctor2:  solute dimensions = 6.608 x 6.745 x 8.708
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 13 x 17 table
Vclist_ctor2:  Using 13 x 13 x 17 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.316, 14.653, 16.616)
Vclist_setupGrid:  Grid lower corner = (-7.346, -7.457, -8.311)
Vclist_assignAtoms:  Have 8927 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001258
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -8.088, -8.1305, -8.003
VPMG::focusFillBound -- New mesh maxs = 7.912, 7.8695, 7.997
VPMG::focusFillBound -- Old mesh mins = -16.088, -16.1305, -16.003
VPMG::focusFillBound -- Old mesh maxs = 15.912, 15.8695, 15.997
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.971800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.014000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.432000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.766800e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.392249e-01
Vprtstp: contraction number = 1.392249e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.686478e-02
Vprtstp: contraction number = 1.211334e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.105234e-03
Vprtstp: contraction number = 1.248301e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.663759e-04
Vprtstp: contraction number = 1.265303e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 3.380220e-05
Vprtstp: contraction number = 1.268966e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.313359e-06
Vprtstp: contraction number = 1.276059e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 5.538063e-07
Vprtstp: contraction number = 1.283933e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.071100e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.468000e-02
Vpmg_setPart:  lower corner = (-8.088, -8.1305, -8.003)
Vpmg_setPart:  upper corner = (7.912, 7.8695, 7.997)
Vpmg_setPart:  actual minima = (-8.088, -8.1305, -8.003)
Vpmg_setPart:  actual maxima = (7.912, 7.8695, 7.997)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.001200e-02
