##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:40 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.016838
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.384400e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 7.800000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.287000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.617100e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.313577e-15
Vprtstp: contraction number = 2.313577e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.290000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.665000e-03
Vpmg_setPart:  lower corner = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  upper corner = (53.3495, 56.54, 65.504)
Vpmg_setPart:  actual minima = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  actual maxima = (53.3495, 56.54, 65.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.575000e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:40 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-42.6505, -39.46, -30.496)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014191
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- New mesh maxs = 37.3495, 40.54, 49.504
VPMG::focusFillBound -- Old mesh mins = -42.6505, -39.46, -30.496
VPMG::focusFillBound -- Old mesh maxs = 53.3495, 56.54, 65.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.818600e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.017000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.421000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.669000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.635000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.361200e-02
Vpmg_setPart:  lower corner = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  upper corner = (37.3495, 40.54, 49.504)
Vpmg_setPart:  actual minima = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  actual maxima = (37.3495, 40.54, 49.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 5.867100e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:40 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-26.6505, -23.46, -14.496)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014436
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -14.6505, -11.46, -2.496
VPMG::focusFillBound -- New mesh maxs = 25.3495, 28.54, 37.504
VPMG::focusFillBound -- Old mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- Old mesh maxs = 37.3495, 40.54, 49.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.954300e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.034700e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.157800e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.810350e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.246000e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.705290e-01
Vpmg_setPart:  lower corner = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  upper corner = (25.3495, 28.54, 37.504)
Vpmg_setPart:  actual minima = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  actual maxima = (25.3495, 28.54, 37.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.012800e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:41 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (11.303, 10.253, 18.556)
Valist_getStatistics:  Min atom coordinate:  (7.231, 6.24, 14.62)
Valist_getStatistics:  Molecule center:  (9.267, 8.2465, 16.588)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (1.977, 0.986, 9.366)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001058
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.387000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.800000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.295000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 9.575000e-03
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.763127e-15
Vprtstp: contraction number = 2.763127e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.400000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.678000e-03
Vpmg_setPart:  lower corner = (-14.733, -16.0035, -7.412)
Vpmg_setPart:  upper corner = (33.267, 31.9965, 40.588)
Vpmg_setPart:  actual minima = (-14.733, -16.0035, -7.412)
Vpmg_setPart:  actual maxima = (33.267, 31.9965, 40.588)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 9.876000e-03
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:41 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (11.303, 10.253, 18.556)
Valist_getStatistics:  Min atom coordinate:  (7.231, 6.24, 14.62)
Valist_getStatistics:  Molecule center:  (9.267, 8.2465, 16.588)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-14.733, -16.0035, -7.412)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (1.977, 0.986, 9.366)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001165
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -6.733, -8.0035, 0.588
VPMG::focusFillBound -- New mesh maxs = 25.267, 23.9965, 32.588
VPMG::focusFillBound -- Old mesh mins = -14.733, -16.0035, -7.412
VPMG::focusFillBound -- Old mesh maxs = 33.267, 31.9965, 40.588
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.290500e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.033000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.519000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.527200e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 7.532129e-02
Vprtstp: contraction number = 7.532129e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 8.470551e-03
Vprtstp: contraction number = 1.124589e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 9.782136e-04
Vprtstp: contraction number = 1.154841e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.148207e-04
Vprtstp: contraction number = 1.173779e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.357311e-05
Vprtstp: contraction number = 1.182113e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.606445e-06
Vprtstp: contraction number = 1.183550e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.904472e-07
Vprtstp: contraction number = 1.185520e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.088900e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.494900e-02
Vpmg_setPart:  lower corner = (-6.733, -8.0035, 0.588)
Vpmg_setPart:  upper corner = (25.267, 23.9965, 32.588)
Vpmg_setPart:  actual minima = (-6.733, -8.0035, 0.588)
Vpmg_setPart:  actual maxima = (25.267, 23.9965, 32.588)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.664400e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:25:41 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (11.303, 10.253, 18.556)
Valist_getStatistics:  Min atom coordinate:  (7.231, 6.24, 14.62)
Valist_getStatistics:  Molecule center:  (9.267, 8.2465, 16.588)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-6.733, -8.0035, 0.588)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (1.977, 0.986, 9.366)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001080
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 1.267, -0.0035, 8.588
VPMG::focusFillBound -- New mesh maxs = 17.267, 15.9965, 24.588
VPMG::focusFillBound -- Old mesh mins = -6.733, -8.0035, 0.588
VPMG::focusFillBound -- Old mesh maxs = 25.267, 23.9965, 32.588
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.890000e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.018000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.397000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.405900e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.253157e-01
Vprtstp: contraction number = 1.253157e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.610987e-02
Vprtstp: contraction number = 1.285543e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.176811e-03
Vprtstp: contraction number = 1.351228e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 3.025090e-04
Vprtstp: contraction number = 1.389689e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 4.323436e-05
Vprtstp: contraction number = 1.429193e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 6.316485e-06
Vprtstp: contraction number = 1.460987e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 9.435390e-07
Vprtstp: contraction number = 1.493772e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.141200e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.536300e-02
Vpmg_setPart:  lower corner = (1.267, -0.0035, 8.588)
Vpmg_setPart:  upper corner = (17.267, 15.9965, 24.588)
Vpmg_setPart:  actual minima = (1.267, -0.0035, 8.588)
Vpmg_setPart:  actual maxima = (17.267, 15.9965, 24.588)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.703100e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:45 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013866
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.971600e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.900000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.457000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.511700e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.299541e-15
Vprtstp: contraction number = 2.299541e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.280000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.820000e-03
Vpmg_setPart:  lower corner = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  upper corner = (48.3425, 48.107, 47.708)
Vpmg_setPart:  actual minima = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  actual maxima = (48.3425, 48.107, 47.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.424400e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:45 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-47.6575, -47.893, -48.292)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.015959
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- New mesh maxs = 32.3425, 32.107, 31.708
VPMG::focusFillBound -- Old mesh mins = -47.6575, -47.893, -48.292
VPMG::focusFillBound -- Old mesh maxs = 48.3425, 48.107, 47.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 3.014800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.045000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.446000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.909300e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.376000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.339600e-02
Vpmg_setPart:  lower corner = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  upper corner = (32.3425, 32.107, 31.708)
Vpmg_setPart:  actual minima = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  actual maxima = (32.3425, 32.107, 31.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.046700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:45 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-31.6575, -31.893, -32.292)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014398
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -19.6575, -19.893, -20.292
VPMG::focusFillBound -- New mesh maxs = 20.3425, 20.107, 19.708
VPMG::focusFillBound -- Old mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- Old mesh maxs = 32.3425, 32.107, 31.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.918200e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.048100e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.988100e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.810530e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.215720e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.659830e-01
Vpmg_setPart:  lower corner = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  upper corner = (20.3425, 20.107, 19.708)
Vpmg_setPart:  actual minima = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  actual maxima = (20.3425, 20.107, 19.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.947640e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:46 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (1.979, 1.874, 2.064)
Valist_getStatistics:  Min atom coordinate:  (-2.093, -2.139, -1.872)
Valist_getStatistics:  Molecule center:  (-0.057, -0.1325, 0.096)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (-7.347, -7.393, -7.126)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001040
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.377000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.800000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.023000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 9.429000e-03
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.812912e-15
Vprtstp: contraction number = 2.812912e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.230000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.372000e-03
Vpmg_setPart:  lower corner = (-24.057, -24.3825, -23.904)
Vpmg_setPart:  upper corner = (23.943, 23.6175, 24.096)
Vpmg_setPart:  actual minima = (-24.057, -24.3825, -23.904)
Vpmg_setPart:  actual maxima = (23.943, 23.6175, 24.096)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 9.586000e-03
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:46 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (1.979, 1.874, 2.064)
Valist_getStatistics:  Min atom coordinate:  (-2.093, -2.139, -1.872)
Valist_getStatistics:  Molecule center:  (-0.057, -0.1325, 0.096)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-24.057, -24.3825, -23.904)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (-7.347, -7.393, -7.126)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002937
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -16.057, -16.3825, -15.904
VPMG::focusFillBound -- New mesh maxs = 15.943, 15.6175, 16.096
VPMG::focusFillBound -- Old mesh mins = -24.057, -24.3825, -23.904
VPMG::focusFillBound -- Old mesh maxs = 23.943, 23.6175, 24.096
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.581400e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.029000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.453000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.816800e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 7.532129e-02
Vprtstp: contraction number = 7.532129e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 8.470551e-03
Vprtstp: contraction number = 1.124589e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 9.782136e-04
Vprtstp: contraction number = 1.154841e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 1.148207e-04
Vprtstp: contraction number = 1.173779e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.357311e-05
Vprtstp: contraction number = 1.182113e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.606445e-06
Vprtstp: contraction number = 1.183550e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.904472e-07
Vprtstp: contraction number = 1.185520e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.098500e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.498900e-02
Vpmg_setPart:  lower corner = (-16.057, -16.3825, -15.904)
Vpmg_setPart:  upper corner = (15.943, 15.6175, 16.096)
Vpmg_setPart:  actual minima = (-16.057, -16.3825, -15.904)
Vpmg_setPart:  actual maxima = (15.943, 15.6175, 16.096)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.953900e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 09:02:46 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 16 atoms
Valist_getStatistics:  Max atom coordinate:  (1.979, 1.874, 2.064)
Valist_getStatistics:  Min atom coordinate:  (-2.093, -2.139, -1.872)
Valist_getStatistics:  Molecule center:  (-0.057, -0.1325, 0.096)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-16.057, -16.3825, -15.904)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 3.58763
Vpbe_ctor2:  solute dimensions = 6.672 x 6.113 x 6.536
Vpbe_ctor2:  solute charge = 0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 13 x 12 x 13 table
Vclist_ctor2:  Using 13 x 12 x 13 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (14.58, 14.521, 14.444)
Vclist_setupGrid:  Grid lower corner = (-7.347, -7.393, -7.126)
Vclist_assignAtoms:  Have 6924 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001051
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -8.057, -8.3825, -7.904
VPMG::focusFillBound -- New mesh maxs = 7.943, 7.6175, 8.096
VPMG::focusFillBound -- Old mesh mins = -16.057, -16.3825, -15.904
VPMG::focusFillBound -- Old mesh maxs = 15.943, 15.6175, 16.096
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.739400e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.005000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.349000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.269600e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.253157e-01
Vprtstp: contraction number = 1.253157e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.610987e-02
Vprtstp: contraction number = 1.285543e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.176811e-03
Vprtstp: contraction number = 1.351228e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 3.025090e-04
Vprtstp: contraction number = 1.389689e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 4.323436e-05
Vprtstp: contraction number = 1.429193e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 6.316485e-06
Vprtstp: contraction number = 1.460987e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 9.435390e-07
Vprtstp: contraction number = 1.493772e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.136000e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.521400e-02
Vpmg_setPart:  lower corner = (-8.057, -8.3825, -7.904)
Vpmg_setPart:  upper corner = (7.943, 7.6175, 8.096)
Vpmg_setPart:  actual minima = (-8.057, -8.3825, -7.904)
Vpmg_setPart:  actual maxima = (7.943, 7.6175, 8.096)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 3.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.422900e-02
