##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:04 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.015049
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.374200e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 7.900000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.212000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.733300e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.313577e-15
Vprtstp: contraction number = 2.313577e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.340000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.607000e-03
Vpmg_setPart:  lower corner = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  upper corner = (53.3495, 56.54, 65.504)
Vpmg_setPart:  actual minima = (-42.6505, -39.46, -30.496)
Vpmg_setPart:  actual maxima = (53.3495, 56.54, 65.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.663400e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-42.6505, -39.46, -30.496)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.015187
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- New mesh maxs = 37.3495, 40.54, 49.504
VPMG::focusFillBound -- Old mesh mins = -42.6505, -39.46, -30.496
VPMG::focusFillBound -- Old mesh maxs = 53.3495, 56.54, 65.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.998100e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.007000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.342000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.360000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.670000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.353900e-02
Vpmg_setPart:  lower corner = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  upper corner = (37.3495, 40.54, 49.504)
Vpmg_setPart:  actual minima = (-26.6505, -23.46, -14.496)
Vpmg_setPart:  actual maxima = (37.3495, 40.54, 49.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.424300e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (13.015, 15.728, 22.964)
Valist_getStatistics:  Min atom coordinate:  (-2.117, 1.352, 12.744)
Valist_getStatistics:  Molecule center:  (5.449, 8.54, 17.854)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-26.6505, -23.46, -14.496)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-7.371, -3.902, 7.49)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014844
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -14.6505, -11.46, -2.496
VPMG::focusFillBound -- New mesh maxs = 25.3495, 28.54, 37.504
VPMG::focusFillBound -- Old mesh mins = -26.6505, -23.46, -14.496
VPMG::focusFillBound -- Old mesh maxs = 37.3495, 40.54, 49.504
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.000820e-01
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.010600e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.051800e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.794980e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.270540e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.716580e-01
Vpmg_setPart:  lower corner = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  upper corner = (25.3495, 28.54, 37.504)
Vpmg_setPart:  actual minima = (-14.6505, -11.46, -2.496)
Vpmg_setPart:  actual maxima = (25.3495, 28.54, 37.504)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.002700e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (35.516, 36.113, 18.631)
Valist_getStatistics:  Min atom coordinate:  (29.301, 31.971, 12.205)
Valist_getStatistics:  Molecule center:  (32.4085, 34.042, 15.418)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (24.047, 26.717, 6.951)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.004426
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 8.976000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.720000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.982000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.988000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.879966e-15
Vprtstp: contraction number = 1.879966e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.240000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 6.488000e-03
Vpmg_setPart:  lower corner = (8.4085, 9.942, -8.582)
Vpmg_setPart:  upper corner = (56.4085, 57.942, 39.418)
Vpmg_setPart:  actual minima = (8.4085, 9.942, -8.582)
Vpmg_setPart:  actual maxima = (56.4085, 57.942, 39.418)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.876800e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (35.516, 36.113, 18.631)
Valist_getStatistics:  Min atom coordinate:  (29.301, 31.971, 12.205)
Valist_getStatistics:  Molecule center:  (32.4085, 34.042, 15.418)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (8.4085, 9.942, -8.582)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (24.047, 26.717, 6.951)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001763
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 16.4085, 17.942, -0.582
VPMG::focusFillBound -- New mesh maxs = 48.4085, 49.942, 31.418
VPMG::focusFillBound -- Old mesh mins = 8.4085, 9.942, -8.582
VPMG::focusFillBound -- Old mesh maxs = 56.4085, 57.942, 39.418
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.443300e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.950000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.316000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.703700e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 5.745445e-02
Vprtstp: contraction number = 5.745445e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 6.550990e-03
Vprtstp: contraction number = 1.140206e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 7.839549e-04
Vprtstp: contraction number = 1.196697e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 9.721139e-05
Vprtstp: contraction number = 1.240012e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.225560e-05
Vprtstp: contraction number = 1.260717e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.555159e-06
Vprtstp: contraction number = 1.268938e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.981992e-07
Vprtstp: contraction number = 1.274463e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.123100e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.506800e-02
Vpmg_setPart:  lower corner = (16.4085, 17.942, -0.582)
Vpmg_setPart:  upper corner = (48.4085, 49.942, 31.418)
Vpmg_setPart:  actual minima = (16.4085, 17.942, -0.582)
Vpmg_setPart:  actual maxima = (48.4085, 49.942, 31.418)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 4.949600e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Mon Jun  7 12:24:05 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (35.516, 36.113, 18.631)
Valist_getStatistics:  Min atom coordinate:  (29.301, 31.971, 12.205)
Valist_getStatistics:  Molecule center:  (32.4085, 34.042, 15.418)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (16.4085, 17.942, -0.582)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (24.047, 26.717, 6.951)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001606
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = 24.4085, 25.942, 7.418
VPMG::focusFillBound -- New mesh maxs = 40.4085, 41.942, 23.418
VPMG::focusFillBound -- Old mesh mins = 16.4085, 17.942, -0.582
VPMG::focusFillBound -- Old mesh maxs = 48.4085, 49.942, 31.418
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.164500e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.890000e-04
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.348000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 5.026400e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.335093e-01
Vprtstp: contraction number = 1.335093e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.619600e-02
Vprtstp: contraction number = 1.213099e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.025080e-03
Vprtstp: contraction number = 1.250358e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.639439e-04
Vprtstp: contraction number = 1.303375e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 3.605146e-05
Vprtstp: contraction number = 1.365876e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 5.158167e-06
Vprtstp: contraction number = 1.430779e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 7.665434e-07
Vprtstp: contraction number = 1.486077e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.120400e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.506000e-02
Vpmg_setPart:  lower corner = (24.4085, 25.942, 7.418)
Vpmg_setPart:  upper corner = (40.4085, 41.942, 23.418)
Vpmg_setPart:  actual minima = (24.4085, 25.942, 7.418)
Vpmg_setPart:  actual maxima = (40.4085, 41.942, 23.418)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 7.330700e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014894
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.164400e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 6.900000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 5.359000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 3.207000e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 2.299541e-15
Vprtstp: contraction number = 2.299541e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 2.260000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 5.716000e-03
Vpmg_setPart:  lower corner = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  upper corner = (48.3425, 48.107, 47.708)
Vpmg_setPart:  actual minima = (-47.6575, -47.893, -48.292)
Vpmg_setPart:  actual maxima = (48.3425, 48.107, 47.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.221000e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-47.6575, -47.893, -48.292)
Vgrid_readDX:  Grid spacings = (8, 8, 8)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.013953
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- New mesh maxs = 32.3425, 32.107, 31.708
VPMG::focusFillBound -- Old mesh mins = -47.6575, -47.893, -48.292
VPMG::focusFillBound -- Old mesh maxs = 48.3425, 48.107, 47.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.948500e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.039000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.508000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 4.713900e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 4.759933e-02
Vprtstp: contraction number = 4.759933e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 5.068016e-03
Vprtstp: contraction number = 1.064724e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 5.713404e-04
Vprtstp: contraction number = 1.127345e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 6.691494e-05
Vprtstp: contraction number = 1.171192e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 8.041374e-06
Vprtstp: contraction number = 1.201731e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 9.831303e-07
Vprtstp: contraction number = 1.222590e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 9.457000e-03
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.353100e-02
Vpmg_setPart:  lower corner = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  upper corner = (32.3425, 32.107, 31.708)
Vpmg_setPart:  actual minima = (-31.6575, -31.893, -32.292)
Vpmg_setPart:  actual maxima = (32.3425, 32.107, 31.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 6.733800e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_receptor.xml
NOsh: Storing potential map 0 path receptor1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (65, 65, 65)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 148 atoms
Valist_getStatistics:  Max atom coordinate:  (8.008, 7.295, 5.168)
Valist_getStatistics:  Min atom coordinate:  (-7.124, -7.081, -5.052)
Valist_getStatistics:  Molecule center:  (0.442, 0.107, 0.058)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-31.6575, -31.893, -32.292)
Vgrid_readDX:  Grid spacings = (2, 2, 2)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 9.60123
Vpbe_ctor2:  solute dimensions = 17.229 x 16.976 x 12.52
Vpbe_ctor2:  solute charge = -8.32667e-16
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 34 x 33 x 25 table
Vclist_ctor2:  Using 34 x 33 x 25 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (25.64, 24.884, 20.728)
Vclist_setupGrid:  Grid lower corner = (-12.378, -12.335, -10.306)
Vclist_assignAtoms:  Have 169349 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.014155
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -19.6575, -19.893, -20.292
VPMG::focusFillBound -- New mesh maxs = 20.3425, 20.107, 19.708
VPMG::focusFillBound -- Old mesh mins = -31.6575, -31.893, -32.292
VPMG::focusFillBound -- Old mesh maxs = 32.3425, 32.107, 31.708
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 9.876800e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (065, 065, 065)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.049900e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (033, 033, 033)
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 3.068400e-02
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.719310e-01
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.150866e-01
Vprtstp: contraction number = 1.150866e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.320271e-02
Vprtstp: contraction number = 1.147198e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 1.600122e-03
Vprtstp: contraction number = 1.211965e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.062989e-04
Vprtstp: contraction number = 1.289270e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 2.842757e-05
Vprtstp: contraction number = 1.377980e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 4.197533e-06
Vprtstp: contraction number = 1.476571e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 6.534564e-07
Vprtstp: contraction number = 1.556763e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.223140e-01
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.676300e-01
Vpmg_setPart:  lower corner = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  upper corner = (20.3425, 20.107, 19.708)
Vpmg_setPart:  actual minima = (-19.6575, -19.893, -20.292)
Vpmg_setPart:  actual maxima = (20.3425, 20.107, 19.708)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 3.910810e-01
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=0)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 1, dime = (13, 13, 13)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (3.484, 2.205, 2.885)
Valist_getStatistics:  Min atom coordinate:  (-2.731, -1.937, -3.541)
Valist_getStatistics:  Molecule center:  (0.3765, 0.134, -0.328)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (-7.985, -7.191, -8.795)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002492
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 5.557000e-03
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (013, 013, 013)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 9.800000e-05
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 7.777000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 1.806600e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.982874e-15
Vprtstp: contraction number = 1.982874e-15
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 3.130000e-04
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 8.281000e-03
Vpmg_setPart:  lower corner = (-23.6235, -23.966, -24.328)
Vpmg_setPart:  upper corner = (24.3765, 24.034, 23.672)
Vpmg_setPart:  actual minima = (-23.6235, -23.966, -24.328)
Vpmg_setPart:  actual maxima = (24.3765, 24.034, 23.672)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 0.000000e+00
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 1.714300e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand0.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (3.484, 2.205, 2.885)
Valist_getStatistics:  Min atom coordinate:  (-2.731, -1.937, -3.541)
Valist_getStatistics:  Molecule center:  (0.3765, 0.134, -0.328)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 13 x 13 x 13 grid
Vgrid_readDX:  Grid origin = (-23.6235, -23.966, -24.328)
Vgrid_readDX:  Grid spacings = (4, 4, 4)
Vgrid_readDX:  allocating 13 x 13 x 13 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (-7.985, -7.191, -8.795)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.002032
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -15.6235, -15.966, -16.328
VPMG::focusFillBound -- New mesh maxs = 16.3765, 16.034, 15.672
VPMG::focusFillBound -- Old mesh mins = -23.6235, -23.966, -24.328
VPMG::focusFillBound -- Old mesh maxs = 24.3765, 24.034, 23.672
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 1.419700e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.041000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.488000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 2.723200e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 5.745445e-02
Vprtstp: contraction number = 5.745445e-02
Vprtstp: iteration = 2
Vprtstp: relative residual = 6.550990e-03
Vprtstp: contraction number = 1.140206e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 7.839549e-04
Vprtstp: contraction number = 1.196697e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 9.721139e-05
Vprtstp: contraction number = 1.240012e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 1.225560e-05
Vprtstp: contraction number = 1.260717e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 1.555159e-06
Vprtstp: contraction number = 1.268938e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 1.981992e-07
Vprtstp: contraction number = 1.274463e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.340900e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.748200e-02
Vpmg_setPart:  lower corner = (-15.6235, -15.966, -16.328)
Vpmg_setPart:  upper corner = (16.3765, 16.034, 15.672)
Vpmg_setPart:  actual minima = (-15.6235, -15.966, -16.328)
Vpmg_setPart:  actual maxima = (16.3765, 16.034, 15.672)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 0.000000e+00
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 5.069900e-02
##############################################################################
# MC-shell I/O capture file.
# Creation Date and Time:  Thu Aug 26 08:59:33 2021

##############################################################################
Hello world from PE 0
Vnm_tstart: starting timer 26 (APBS WALL CLOCK)..
NOsh_parseInput:  Starting file parsing...
NOsh: Parsing READ section
NOsh: Storing molecule 0 path hostguest_ligand.xml
NOsh: Storing potential map 0 path ligand1.dx
NOsh: Done parsing READ section
NOsh: Done parsing READ section (nmol=1, ndiel=0, nkappa=0, ncharge=0, npot=1)
NOsh: Parsing ELEC section
NOsh_parseMG: Parsing parameters for MG calculation
NOsh_parseMG:  Parsing dime...
PBEparm_parseToken:  trying dime...
MGparm_parseToken:  trying dime...
NOsh_parseMG:  Parsing glen...
PBEparm_parseToken:  trying glen...
MGparm_parseToken:  trying glen...
NOsh_parseMG:  Parsing gcent...
PBEparm_parseToken:  trying gcent...
MGparm_parseToken:  trying gcent...
NOsh_parseMG:  Parsing mol...
PBEparm_parseToken:  trying mol...
NOsh_parseMG:  Parsing lpbe...
PBEparm_parseToken:  trying lpbe...
NOsh: parsed lpbe
NOsh_parseMG:  Parsing usemap...
PBEparm_parseToken:  trying usemap...
PBEparm_parseToken:  Read pot...
NOsh_parseMG:  Parsing bcfl...
PBEparm_parseToken:  trying bcfl...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing ion...
PBEparm_parseToken:  trying ion...
NOsh_parseMG:  Parsing pdie...
PBEparm_parseToken:  trying pdie...
NOsh_parseMG:  Parsing sdie...
PBEparm_parseToken:  trying sdie...
NOsh_parseMG:  Parsing srfm...
PBEparm_parseToken:  trying srfm...
NOsh_parseMG:  Parsing chgm...
PBEparm_parseToken:  trying chgm...
MGparm_parseToken:  trying chgm...
NOsh_parseMG:  Parsing sdens...
PBEparm_parseToken:  trying sdens...
NOsh_parseMG:  Parsing srad...
PBEparm_parseToken:  trying srad...
NOsh_parseMG:  Parsing temp...
PBEparm_parseToken:  trying temp...
NOsh_parseMG:  Parsing write...
PBEparm_parseToken:  trying write...
NOsh_parseMG:  Parsing end...
MGparm_check:  checking MGparm object of type 0.
NOsh:  nlev = 4, dime = (33, 33, 33)
NOsh: Done parsing ELEC section (nelec = 1)
NOsh: Done parsing file (got QUIT)
Valist_readXML: Counted 22 atoms
Valist_getStatistics:  Max atom coordinate:  (3.484, 2.205, 2.885)
Valist_getStatistics:  Min atom coordinate:  (-2.731, -1.937, -3.541)
Valist_getStatistics:  Molecule center:  (0.3765, 0.134, -0.328)
NOsh_setupCalc:  Mapping ELEC statement 0 (1) to calculation 0 (1)
Vgrid_readDX:  Grid dimensions 33 x 33 x 33 grid
Vgrid_readDX:  Grid origin = (-15.6235, -15.966, -16.328)
Vgrid_readDX:  Grid spacings = (1, 1, 1)
Vgrid_readDX:  allocating 33 x 33 x 33 doubles for storage
Vnm_tstart: starting timer 27 (Setup timer)..
Setting up PBE object...
Vpbe_ctor2:  solute radius = 5.41618
Vpbe_ctor2:  solute dimensions = 8.815 x 6.942 x 9.026
Vpbe_ctor2:  solute charge = -0.0001
Vpbe_ctor2:  bulk ionic strength = 0
Vpbe_ctor2:  xkappa = 0
Vpbe_ctor2:  Debye length = 0
Vpbe_ctor2:  zkappa2 = 0
Vpbe_ctor2:  zmagic = 7042.98
Vpbe_ctor2:  Constructing Vclist with 17 x 13 x 18 table
Vclist_ctor2:  Using 17 x 13 x 18 hash table
Vclist_ctor2:  automatic domain setup.
Vclist_ctor2:  Using 2 max radius
Vclist_setupGrid:  Grid lengths = (16.723, 14.65, 16.934)
Vclist_setupGrid:  Grid lower corner = (-7.985, -7.191, -8.795)
Vclist_assignAtoms:  Have 12595 atom entries
Vacc_storeParms:  Surf. density = 10
Vacc_storeParms:  Max area = 172.034
Vacc_storeParms:  Using 1740-point reference sphere
Setting up PDE object...
Vpmp_ctor2:  Using meth = 2, mgsolv = 1
Setting PDE center to local center...
Vpmg_fillco:  filling in source term.
fillcoCharge:  Calling fillcoChargeSpline2...
Vpmg_fillco:  filling in source term.
Vpmg_fillco:  marking ion and solvent accessibility.
fillcoCoef:  Calling fillcoCoefMol...
Vacc_SASA: Time elapsed: 0.001702
Vpmg_fillco:  done filling coefficient arrays
Vpmg_fillco:  filling boundary arrays
Vpmg_fillco:  filling in source term.
VPMG::focusFillBound -- New mesh mins = -7.6235, -7.966, -8.328
VPMG::focusFillBound -- New mesh maxs = 8.3765, 8.034, 7.672
VPMG::focusFillBound -- Old mesh mins = -15.6235, -15.966, -16.328
VPMG::focusFillBound -- Old mesh maxs = 16.3765, 16.034, 15.672
Vpmg_fillco:  done filling boundary arrays
Vnm_tstop: stopping timer 27 (Setup timer).  CPU TIME = 2.226700e-02
Vnm_tstart: starting timer 28 (Solver timer)..
Vnm_tstart: starting timer 30 (Vmgdrv2: fine problem setup)..
Vbuildops: Fine: (033, 033, 033)
Vbuildops: Operator stencil (lev, numdia) = (1, 4)
Vnm_tstop: stopping timer 30 (Vmgdrv2: fine problem setup).  CPU TIME = 1.067000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: coarse problem setup)..
Vbuildops: Galer: (017, 017, 017)
Vbuildops: Galer: (009, 009, 009)
Vbuildops: Galer: (005, 005, 005)
Vnm_tstop: stopping timer 30 (Vmgdrv2: coarse problem setup).  CPU TIME = 2.688000e-03
Vnm_tstart: starting timer 30 (Vmgdrv2: solve)..
Vnm_tstop: stopping timer 40 (MG iteration).  CPU TIME = 6.083200e-02
Vprtstp: iteration = 0
Vprtstp: relative residual = 1.000000e+00
Vprtstp: contraction number = 1.000000e+00
Vprtstp: iteration = 1
Vprtstp: relative residual = 1.335093e-01
Vprtstp: contraction number = 1.335093e-01
Vprtstp: iteration = 2
Vprtstp: relative residual = 1.619600e-02
Vprtstp: contraction number = 1.213099e-01
Vprtstp: iteration = 3
Vprtstp: relative residual = 2.025080e-03
Vprtstp: contraction number = 1.250358e-01
Vprtstp: iteration = 4
Vprtstp: relative residual = 2.639439e-04
Vprtstp: contraction number = 1.303375e-01
Vprtstp: iteration = 5
Vprtstp: relative residual = 3.605146e-05
Vprtstp: contraction number = 1.365876e-01
Vprtstp: iteration = 6
Vprtstp: relative residual = 5.158167e-06
Vprtstp: contraction number = 1.430779e-01
Vprtstp: iteration = 7
Vprtstp: relative residual = 7.665434e-07
Vprtstp: contraction number = 1.486077e-01
Vnm_tstop: stopping timer 30 (Vmgdrv2: solve).  CPU TIME = 1.143500e-02
Vnm_tstop: stopping timer 28 (Solver timer).  CPU TIME = 1.576500e-02
Vpmg_setPart:  lower corner = (-7.6235, -7.966, -8.328)
Vpmg_setPart:  upper corner = (8.3765, 8.034, 7.672)
Vpmg_setPart:  actual minima = (-7.6235, -7.966, -8.328)
Vpmg_setPart:  actual maxima = (8.3765, 8.034, 7.672)
Vpmg_setPart:  bflag[FRONT] = 0
Vpmg_setPart:  bflag[BACK] = 0
Vpmg_setPart:  bflag[LEFT] = 0
Vpmg_setPart:  bflag[RIGHT] = 0
Vpmg_setPart:  bflag[UP] = 0
Vpmg_setPart:  bflag[DOWN] = 0
Vnm_tstart: starting timer 29 (Energy timer)..
Vnm_tstop: stopping timer 29 (Energy timer).  CPU TIME = 1.000000e-06
Vnm_tstart: starting timer 30 (Force timer)..
Vnm_tstop: stopping timer 30 (Force timer).  CPU TIME = 1.000000e-06
Vgrid_writeDX:  Opening virtual socket...
Vgrid_writeDX:  Writing to virtual socket...
Vgrid_writeDX:  Writing comments for ASC format.
Vnm_tstop: stopping timer 26 (APBS WALL CLOCK).  CPU TIME = 8.277000e-02
